### ISSUE TITLE
Allow contributors the ability to create branches and PR's.

### ISSUE THREAD

**Issue by JonyTek** [dasiths/SimpleEndpoints#2]
Hi mate,

I found this little project on Twitter earlier today and really liked the idea. Since I am in lockdown at the moment I thought I would pull the code and see what I could come up with to help. 

The first thing I did was add Swashbuckle so I could visualise what was going on, there were a few issues with this. The main one was that the `Swahbuckle.AspNet` library does not consider inherited attributes when scanning routes which was a problem. I solved this by tapping into the `IApiDescriptionGroupCollectionProvider` and setting the `HttpMethod`. This gave me an idea that we could do away with the `HttpVerb` attributes on all endpoints and I have achieved this by setting a marker interface on each of the 4 abstract verb scoped endpoints and then looking at the inheritance tree during applying the `EndpointRoutingConvention`. I have also included the ability to set a global route segment `api/` as an example and also set a naming convention token to be used for registering the routes against endpoint names.

Anyway, if you are interested in having me create a PR please go ahead and open up permissions for non-master branches.

I look forward to hearing from you. I have a couple more ideas how we may be able to make this a really cool little library.

Cool & thanks.

Jony.

**Comment by dasiths** [comment]
Hey mate,
Thanks a great idea and I was actually thinking of a way to do it myself. I started out with the project with the `HandleAsync` method being protected and each endpoint convention implementing a Get(), Post(), etc public methods that call `HandleAsync`.

The current solution I have exhibits the problem you mentioned though. I really like your idea of having the best of both worlds. 

I'll give the necessary permissions for a PR now.

Love your work.

Dasith

**Comment by dasiths** [comment]
I've implemented the swashbuckle feature just now. Have a look and let me know what you think?

**Comment by dasiths** [comment]
Closing this as the permissions have been set.
